// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApoRNdty0KTF2rRcrcJjTgsYdmjfVHLeQ',
    appId: '1:645584422563:web:86a55aed44d14f8ff5e116',
    messagingSenderId: '645584422563',
    projectId: 'movora-ade4c',
    authDomain: 'movora-ade4c.firebaseapp.com',
    storageBucket: 'movora-ade4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlrB2oG8F5c57OIwokFxtrHtuohEa-0T0',
    appId: '1:645584422563:android:aa97741ee949dbc8f5e116',
    messagingSenderId: '645584422563',
    projectId: 'movora-ade4c',
    storageBucket: 'movora-ade4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeMg_sA7ZvVGRywvZ1v88LR-xcqY1vhIA',
    appId: '1:645584422563:ios:6984bcca25d5c6b6f5e116',
    messagingSenderId: '645584422563',
    projectId: 'movora-ade4c',
    storageBucket: 'movora-ade4c.firebasestorage.app',
    androidClientId: '645584422563-7qhnsmc25eealdusp07ghljeveeana7q.apps.googleusercontent.com',
    iosClientId: '645584422563-oj1ebvs5oo6t9k236u6j6rt45qn79ff9.apps.googleusercontent.com',
    iosBundleId: 'com.example.movoraUser',
  );

}